import { LogLevel as InsightLogLevel, InsightEngine, InsightEngineConfiguration } from '@coveo/headless/insight';
import { i18n } from 'i18next';
import { InitializeEvent } from '../../../utils/initialization-utils';
import { CommonBindings, NonceBindings } from '../../common/interface/bindings';
import { StencilBaseAtomicInterface } from '../../common/interface/interface-common-stencil';
import { InsightStore } from './store';
export type InsightInitializationOptions = InsightEngineConfiguration;
export type InsightBindings = CommonBindings<InsightEngine, InsightStore, HTMLAtomicInsightInterfaceElement> & NonceBindings;
/**
 * @internal
 */
export declare class AtomicInsightInterface implements StencilBaseAtomicInterface<InsightEngine> {
    private initialized;
    error?: Error;
    /**
     * The service insight interface headless engine.
     */
    engine?: InsightEngine;
    /**
     * Whether analytics should be enabled.
     */
    analytics: boolean;
    /**
     * The service insight interface i18next instance.
     */
    i18n: i18n;
    /**
     * The severity level of the messages to log in the console.
     */
    logLevel?: InsightLogLevel;
    /**
     * The service insight interface language.
     */
    language: string;
    /**
     * The language assets path. By default, this will be a relative URL pointing to `./lang`.
     *
     * Example: "/mypublicpath/languages"
     *
     */
    languageAssetsPath: string;
    /**
     * The icon assets path. By default, this will be a relative URL pointing to `./assets`.
     *
     * Example: "/mypublicpath/icons"
     *
     */
    iconAssetsPath: string;
    /**
     * A list of non-default fields to include in the query results.
     *
     * Specify the property as an array using a JSON string representation:
     * ```html
     * <atomic-insight-interface fields-to-include='["fieldA", "fieldB"]'></atomic-insight-interface>
     * ```
     */
    fieldsToInclude: string[] | string;
    /**
     * The number of results per page. By default, this is set to `5`.
     */
    resultsPerPage: number;
    /**
     * The value to set the [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce) attribute to on inline script and style elements generated by this interface and its child components.
     * If your application is served with a Content Security Policy (CSP) that doesn't include the `script-src: 'unsafe-inline'` or `style-src: 'unsafe-inline'` directives,
     * you should ensure that your application server generates a new nonce on every page load and uses the generated value to set this prop and serve the corresponding CSP response headers
     * (i.e., script-src 'nonce-<YOUR_GENERATED_NONCE>' and style-src 'nonce-<YOUR_GENERATED_NONCE>').
     * Otherwise you may see console errors such as
     *  - Refused to execute inline script because it violates the following Content Security Policy directive: [...]
     *  - Refused to apply inline style because it violates the following Content Security Policy directive: [...].
     * When using a nonce, the first import of Atomic should be to import & call the `setNonce` function with the generated nonce value.
     * @example:
     * ```html
     * <script nonce="<YOUR_GENERATED_NONCE>">
     *  import {setNonce} from '@coveo/atomic';
     *  setNonce('<YOUR_GENERATED_NONCE>');
     * </script>
     * ```
     */
    CspNonce?: string;
    host: HTMLAtomicInsightInterfaceElement;
    private store;
    private commonInterfaceHelper;
    private i18Initialized;
    private componentWillLoadCalledPromise;
    private componentWillLoadResolver;
    constructor();
    connectedCallback(): void;
    componentWillLoad(): void;
    private initResultsPerPage;
    registerFieldsToInclude(): void;
    /**
     * Initializes the connection with the headless insight engine using options for `accessToken` (required), `organizationId` (required), `environment` (defaults to `prod`), and `renewAccessToken`.
     */
    initialize(options: InsightInitializationOptions): Promise<void>;
    /**
     * Initializes the connection with an already preconfigured headless insight engine.
     *
     */
    initializeWithInsightEngine(engine: InsightEngine): Promise<void>;
    /**
     *
     * Executes the first search and logs the interface load event to analytics, after initializing connection to the headless search engine.
     */
    executeFirstSearch(): Promise<void>;
    updateIconAssetsPath(): void;
    handleInitialization(event: InitializeEvent): void;
    updateLanguage(): Promise<void>;
    toggleAnalytics(): void;
    get bindings(): InsightBindings;
    private initEngine;
    private internalInitialization;
    render(): any;
}
